"""initial

Revision ID: 23c3b017b961
Revises: 
Create Date: 2026-09-24 10:40:34.434428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c3b017b961'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=254), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_identifier'), ['identifier'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('organization_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_organizations_user_name')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_user_id'), ['user_id'], unique=False)

    op.create_table('generated_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('requirements_hash', sa.String(length=64), nullable=False),
    sa.Column('methodology', sa.String(length=120), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_designs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_designs_organization_id'), ['organization_id'], unique=True)

    op.create_table('network_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('branches', sa.Integer(), nullable=False),
    sa.Column('buildings', sa.Integer(), nullable=False),
    sa.Column('floors_per_building', sa.Integer(), nullable=False),
    sa.Column('branch_users_percent', sa.Integer(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=False),
    sa.Column('wired_devices', sa.Integer(), nullable=False),
    sa.Column('wireless_devices', sa.Integer(), nullable=False),
    sa.Column('servers', sa.Integer(), nullable=False),
    sa.Column('printers', sa.Integer(), nullable=False),
    sa.Column('voip_phones', sa.Integer(), nullable=False),
    sa.Column('cctv_cameras', sa.Integer(), nullable=False),
    sa.Column('iot_devices', sa.Integer(), nullable=False),
    sa.Column('internet', sa.Boolean(), nullable=False),
    sa.Column('guest_wifi', sa.Boolean(), nullable=False),
    sa.Column('staff_wifi', sa.Boolean(), nullable=False),
    sa.Column('voip', sa.Boolean(), nullable=False),
    sa.Column('cctv', sa.Boolean(), nullable=False),
    sa.Column('iot', sa.Boolean(), nullable=False),
    sa.Column('high_availability', sa.Boolean(), nullable=False),
    sa.Column('scalability', sa.Boolean(), nullable=False),
    sa.Column('expected_growth_percent', sa.Integer(), nullable=False),
    sa.Column('budget_level', sa.String(length=10), nullable=False),
    sa.Column('budget_amount_usd', sa.Float(), nullable=True),
    sa.Column('security_level', sa.String(length=10), nullable=False),
    sa.Column('performance_level', sa.String(length=10), nullable=False),
    sa.Column('addressing_method', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_requirements_organization_id'), ['organization_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_requirements_organization_id'))

    op.drop_table('network_requirements')
    with op.batch_alter_table('generated_designs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_designs_organization_id'))

    op.drop_table('generated_designs')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_user_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_identifier'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
